# .streamlit/secrets.toml
# ⚠️ Never push this file to GitHub — it's in .gitignore
 
GEMINI_API_KEY = "AIzaSyBiIhXGjHIbdfzCH81PPaMEmVU2TYKfl0g"     
DB_USER = "postgres"
DB_PASS = "om*7489"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "bhopal_smart_city"